ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Copy the given directory containing the SlingShot/CXI libraries into
# the container at /container/ss11-libs and add that to the LD_LIBRARY_PATH.
# This allows users to pull in the host libs now rather than at container rt.
ARG HPC_LIBS_DIR
ARG HPC_DIR=/container/hpc
COPY ${HPC_LIBS_DIR} /tmp/ss11-libs
RUN ls /tmp
RUN ARCH_TYPE=`uname -m` && \
    mkdir -p ${HPC_DIR}/lib && \
    cp -r /tmp/ss11-libs/* ${HPC_DIR}/lib && \
    chmod -R go+rX ${HPC_DIR}/lib && \
    rm -rf /tmp/ss11-libs && \
    ln -s /usr/lib/${ARCH_TYPE}-linux-gnu/libjson-c.so.5 \
       /usr/lib/${ARCH_TYPE}-linux-gnu/libjson-c.so.3

ENV LD_LIBRARY_PATH=${HPC_LIB}/lib:$LD_LIBRARY_PATH

RUN rm -rf /tmp/*
